server:
  port: 8002
spring:
  application:
    name: cloud-payment-service
  datasource:
    typeL: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2021?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234qwer

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pojer.home.springcloud.entities

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka