server:
  port: 7002

eureka:
  instance:
    hostname: eurekapojer
  #    hostname: eureka7002.com
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7001/eureka/